# Generated by Django 5.0.3 on 2024-04-02 15:50

import fake_elecciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fake_elecciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/', validators=[fake_elecciones.models.validate_csv_file_extension])),
            ],
        ),
    ]
